### PR TITLE
Porting EnSight scripts to PyEnSight documentation

### PR DESCRIPTION
**Pull request by mariostieriansys**
A proposed section to cover the porting of existing EnSight scripts into PyEnSight

@randallfrank please check if I have missed something, if we need more details, if I have said something wrong
@PipKat this is an important area of our documentation, so any help would be much appreciated

### CODE REVIEW

**Comment by mariostieriansys** [comment]
VSCode RST preview

image

**Comment by PipKat** [comment]
@mariostieriansys I can take some time tomorrow to review the doc. Do you want me to wait until you get all checks running and then check out this branch? Or, should I check it out as is and try to fix the checks that have failed?

**Comment by mariostieriansys** [comment]
@PipKat I have fixed the errors

**Review by PipKat — COMMENTED** [review]
I pushed my editorial changes.

**Review by randallfrank — APPROVED** [review]

**Pull request merged**
